
version: 8.16.0-SNAPSHOT
#
count: 1

# monitoring:
#   metrics:
#     elasticsearchRefs:
#       - name: elasticsearch-monitoring

pipelines:
  - pipeline.id: main
    config.string: |
      input {
        beats {
          port => 5044
        }
      }
      }
      output {
        elasticsearch {
          hosts => [ "${ECK_ES_HOSTS}" ]
          user => "${ECK_ES_USER}"
          password => "${ECK_ES_PASSWORD}"
          ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
        }
      }

elasticsearchRefs:
  - clusterName: eck
    name: elasticsearch

services:
  - name: beats
    service:
      spec:
        type: ClusterIP
        ports:
          - port: 5044
            name: "filebeat"
            protocol: TCP
            targetPort: 5044

